name: medPilot
description: MedPilot” --org com.hospice.medPilot”
version: 1.0.5+16
publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: 3.7.11

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.7.2
  flutter_easyloading: ^3.0.5
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.7+1
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.0+1
  dropdown_button2: ^2.3.9
  link_text: ^0.2.1
  package_info_plus: ^8.3.0
  pretty_dio_logger: ^1.4.0
  signalr_netcore: ^1.4.3
  geolocator: ^14.0.0
  location: ^8.0.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  another_flushbar: ^1.12.30
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  photo_view: ^0.14.0
  font_awesome_flutter: ^10.8.0
  youtube_player_flutter: ^9.1.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer_animation: ^2.2.2
  flutter_html: ^3.0.0


#dependency_overrides:
#  package_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/med/
    - assets/translations/


  fonts:
    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
