class AppStrings {
  static const String password = "password";
  static const String badRequestError = "badRequestError";
  static const String noContent = "noContent";
  static const String forbiddenError = "forbiddenError";
  static const String unauthorizedError = "unauthorizedError";
  static const String notFoundError = "notFoundError";
  static const String internalServerError = "internalServerError";
  static const String timeoutError = "timeoutError";
  static const String defaultError = "defaultError";
  static const String noInternetError = "noInternetError";
  static const String noInternetConnection = "noInternetConnection";
  static const String moreLoad = "moreLoad";
  static const String exitAppAlertTitle = "exitAppAlertTitle";
  static const String noPageFound = "noPageFound";
  static const String email = "email";
  static const String provideValidNumber = "provideValidNumber";
  static const String logOut = "logOut";
  static const String home = "home";


  static const String forgotPassword = "Forgot Password?";
  static const String login = "Login";
  static const String dontHaveAnAccount = "Don't have an account?";
  static const String signUp = "Sign Up";
  static const String enterEmail = "Enter Email";
  static const String enterPassword = "Enter Password";
  static const String or = "OR";
  static const String wrongCredential = "Email or Password Incorrect";
  static const String myCart = "My Cart";

  // prescription
  static const String years = "years";
  static const String lastUpdate = "Last Update";
  static const String diagnosis = "Diagnosis";
  static const String medications = "Medications";
  static const String advice = "Advice";
  static const String vitalSign = "Vital Signs";
  static const String physicalSymptoms = "Physical Symptoms";
  static const String painClinic = "Pain Clinic";
  static const String location = "Location";
  static const String radiation = "Radiation";
  static const String severity = "Severity";
  static const String pattern = "Pattern";
  static const String relievingFactor = "Relieving Factors";
  static const String suspectedCause = "Suspected Cause";
  static const String viewDetails = "View Details";
  static const String close = "Close";
  static const String painDetails = "Pain Details";
  static const String painAssessmentHistory = "Pain Assessment History";
  static const String medication = "Medication";
  static const String assessment = "Assessment";
  static const String dosage = "Dosage";
  static const String instructions = "Instructions";
  static const String doseSchedule = "Dose Schedule";
  static const String tapToViewSchedule = "Tap to view schedule";
  static const String markTaken = "Mark Taken";
  static const String newPainAssessment = "New Pain Assessment";
  static const String recordYourPainDetails = "Record your pain details";
  static const String savedSuccessfullyCreated = "Follow-up record saved successfully.";
  static const String savedSuccessfully = "Saved successfully.";
  static const String submitAssessment = "Submit Assessment";
  static const String management = "Management";
  static const String woundManagementReport = "Wound Management Report";
  static const String woundSummery = "Wound Summary";
  static const String totalWounds = "Total Wounds";
  static const String activeCases = "Active Cases";
  static const String burns = "Burns";
  static const String bedSores = "Bed Sores";
  static const String site = "Site";
  static const String firstOccurred = "First Occurred";
  static const String date = "Date";
  static const String debridement = "Debridement";
  static const String cleaningSolution = "Cleaning Solution";
  static const String productUsed = "Product Used";
  static const String dressingFrequency = "Dressing Frequency";
  static const String nextReview = "Next Review";

}
